-- Criar tabela para registrar todas as alterações vindas da Matriz
CREATE TABLE public.matriz_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    entity_type TEXT NOT NULL, -- 'unidade' ou 'franqueado'
    entity_id UUID NOT NULL,
    action TEXT NOT NULL, -- 'created' ou 'updated'
    changes JSONB, -- Armazena o que mudou (ex: {"de": "valor_antigo", "para": "valor_novo"})
    raw_payload JSONB -- O payload completo recebido do webhook para referência
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.matriz_audit_log ENABLE ROW LEVEL SECURITY;

-- Política de Segurança: Apenas administradores podem ver os logs de auditoria.
CREATE POLICY "allow_read_for_admins" ON public.matriz_audit_log
FOR SELECT TO authenticated USING (
  (SELECT perfil FROM public.usuarios_internos WHERE user_id = auth.uid()) = 'admin'
);