-- Cria a tabela para armazenar os vínculos entre franqueados e unidades
CREATE TABLE public.franqueados_unidades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  franqueado_id UUID NOT NULL REFERENCES public.franqueados(id) ON DELETE CASCADE,
  unidade_id UUID NOT NULL REFERENCES public.unidades(id) ON DELETE CASCADE,
  ativo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (franqueado_id, unidade_id)
);

-- Habilita a segurança a nível de linha (RLS)
ALTER TABLE public.franqueados_unidades ENABLE ROW LEVEL SECURITY;

-- Permite que qualquer usuário autenticado leia os vínculos (essencial para o sistema)
CREATE POLICY "Permitir leitura para usuários autenticados"
ON public.franqueados_unidades
FOR SELECT TO authenticated
USING (true);

-- Cria os índices para otimizar as buscas
CREATE INDEX IF NOT EXISTS idx_franq_unid_franqueado_id ON public.franqueados_unidades(franqueado_id);
CREATE INDEX IF NOT EXISTS idx_franq_unid_unidade_id ON public.franqueados_unidades(unidade_id);

-- Cria o gatilho para atualizar a coluna 'updated_at' automaticamente
CREATE TRIGGER handle_updated_at
BEFORE UPDATE ON public.franqueados_unidades
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();